myArray = [2, 4, 5, 6]
print(myArray)
print('Size: len(myArray) ', len(myArray))
print('Capacity: Python arrays are dynamic arrays')
print('is_empty: len(myArray)==0 ', len(myArray) == 0)
print('at(1) myArray[1]', myArray[1])
print('push(item): myArray.append(7)')
myArray.append(7)
print(myArray)
print('insert(index,item): myArray.insert(1, 3)')
myArray.insert(1, 3)
print(myArray)
print('prepend(item): myArray.insert(0, 1)')
myArray.insert(0, 1)
print(myArray)
print('pop(): myArray.pop()', myArray.pop())
print(myArray)
print('delete(index): myArray.pop(2)', myArray.pop(2))
print(myArray)
print('remove(item): myArray.remove(6)')
myArray.remove(6)
print(myArray)
print('resize(new_capacity): Python arrays are dynamic arrays')
