from linked_list import LinkedList


def main():
    my_linked_list = LinkedList()
    print('my_linked_list.empty():', my_linked_list.empty())
    print('Pushing 10 and 20 to front')
    my_linked_list.push_front(10)
    my_linked_list.push_front(20)
    print("My Linked List: ", my_linked_list)
    print("my_linked_list.size(): ", my_linked_list.size())
    print('my_linked_list.empty():', my_linked_list.empty())
    print('Pushing 5 and 0 to back')
    my_linked_list.push_back(5)
    my_linked_list.push_back(0)
    print("My Linked List: ", my_linked_list)
    print('my_linked_list.pop_front(): ', my_linked_list.pop_front())
    print("My Linked List: ", my_linked_list)
    print('my_linked_list.pop_back(): ', my_linked_list.pop_back())
    print("My Linked List: ", my_linked_list)
    print('my_linked_list.front(): ', my_linked_list.front())
    print('my_linked_list.back(): ', my_linked_list.back())
    print("My Linked List: ", my_linked_list)
    print('my_lined_list.insert(1, 7): ', my_linked_list.insert(1, 7))
    print("My Linked List: ", my_linked_list)
    print('my_lined_list.insert(2, 101): ', my_linked_list.insert(2, 101))
    print("My Linked List: ", my_linked_list)
    print('my_linked_list.value_at(2): ', my_linked_list.value_at(2))
    # print('my_linked_list.value_at(5): ', my_linked_list.value_at(5))
    print('my_linked_list.erase(2)')
    my_linked_list.erase(2)
    print("My Linked List: ", my_linked_list)
    print('my_linked_list.remove_value(7)')
    my_linked_list.remove_value(7)
    print("My Linked List: ", my_linked_list)
    print('my_linked_list.remove_value(10)')
    my_linked_list.remove_value(10)
    print("My Linked List: ", my_linked_list)
    print('my_linked_list.size(): ', my_linked_list.size())
    print('Pushing 15 and 20 to back')
    my_linked_list.push_back(15)
    #my_linked_list.push_back(20)
    print("My Linked List: ", my_linked_list)
    print(my_linked_list.reverse())
    print("My Linked List: ", my_linked_list)



if __name__ == '__main__':
    main()
